# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  gradle: circleci/gradle@6.3
workflows:
  checkout-build-test:
    jobs:
      - gradle/test
